### ISSUE TITLE
Dynamic Asset Loading

### ISSUE THREAD

**Issue by speedaemon** [gladiusio/gladius-masternode#10]
## First time the route is seen by the masternode
For all pages with linked assets, every supported asset's `src` / `href` attributes will be removed and a gladiusID attribute will be added, the page along with all of it's supported assets will be copied to the content nodes. The master node also stores the SHA256 of the stripped page and the assets for later verification. 

## When the page is loaded 
The page is loaded in the browser by the masternode JS which verifies the hash of the incoming HTML. This then loads the various assets by their gladiusID attribute and also verifies their hash.

## Other things to think about
Rendering the base64 encoded css from the content node before we render the rest of the page. This probably means that CSS will need to be specially added as a link by the masternode rather than it's html being loaded from the content node.

**Comment by alex-godwin** [comment]
## Things to add
- The various assets are all base64 encoded on the content node
- The masternode sends the content node and the expected hashes with the loader JS to the browser
- To elaborate on the CSS issue, we can't modify the `<head>` after it loads, so we will probably have to load the CSS from the content node before we load the body and then other assets to prevent the page from popping in with no style.

**Comment by speedaemon** [comment]
Discussed with Alex about using IndexDB to store assets instead of inline base64

**Comment by speedaemon** [comment]
Considering the possibility of using an iframe to render page content so that a new <head> can be written after initial HTML content is fetched
